# Generated by Django 4.2.1 on 2023-05-10 11:38

import authentication.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="otp_secret_key",
            field=models.PositiveIntegerField(default=678239),
            preserve_default=False,
        ),
    ]
