# Generated by Django 4.2.1 on 2023-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_managers_user_otp_secret_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp_secret_key",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
