# Generated by Django 4.2.1 on 2023-05-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watches", "0002_brand_watch_created_at_watch_modified_at_wishlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
