# Generated by Django 4.1.3 on 2023-08-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watches", "0005_watch_likes_delete_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified_at"),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("AT", "Austria"),
                            ("BR", "Brazil"),
                            ("BG", "Bulgaria"),
                            ("CA", "Canada"),
                            ("CZ", "Czech Republic"),
                            ("FR", "France"),
                            ("DE", "Germany"),
                            ("GR", "Greece"),
                            ("IT", "Italy"),
                            ("JP", "Japan"),
                            ("NO", "Norway"),
                            ("PL", "Poland"),
                            ("SG", "Singapore"),
                            ("ES", "Spain"),
                            ("SE", "Sweden"),
                            ("CH", "Switzerland"),
                            ("NL", "Netherlands"),
                            ("AE", "United Arab Emirates"),
                            ("UK", "United Kingdom"),
                            ("US", "United States"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("rolex", "Rolex"),
                            ("iwc", "IWC"),
                            ("omega", "Omega"),
                            ("breitling", "Breitling"),
                            ("audemarspiguet", "Audemars Piguet"),
                            ("hublot", "Hublot"),
                            ("panerai", "Panerai"),
                            ("patekphilippe", "Patek Philippe"),
                            ("tudor", "Tudor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "per_page",
                    models.IntegerField(
                        choices=[
                            (30, "Thirty"),
                            (60, "Sixty"),
                            (120, "One Hundred Twenty"),
                        ],
                        default=30,
                    ),
                ),
                ("max_pages", models.IntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
