# Generated by Django 4.1.3 on 2023-08-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watches", "0007_alter_task_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="gender",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
